SELECT country.CONTINENT, FLOOR(AVG(city.POPULATION))
FROM COUNTRY AS country
    LEFT JOIN CITY AS city ON (CITY.COUNTRYCODE = COUNTRY.CODE)
    WHERE city.POPULATION IS NOT NULL GROUP BY country.CONTINENT
