" SAMPLE "
SELECT N, IF(P IS NULL, 'Root', 'Leaf')
FROM BST AS B
ORDER BY N;        

SELECT COUNT(*) FROM BST;
SELECT COUNT(*) FROM BST WHERE P=2;

" Solution "
SELECT N, IF(P IS NULL, 'Root', IF((SELECT COUNT(*) FROM BST WHERE P=B.N)>0, 'Inner', 'Leaf'))
FROM BST AS B
ORDER BY N;



" Table "
CREATE TABLE BST (
    N integer,
    P integer
);

INSERT INTO BST VALUES (1, 2);
INSERT INTO BST VALUES (3, 2);
INSERT INTO BST VALUES (6, 8);
INSERT INTO BST VALUES (9, 8);
INSERT INTO BST VALUES (2, 5);
INSERT INTO BST VALUES (8, 5);
INSERT INTO BST VALUES (5, null);
